auto-patch: improve error handling

diff --git a/auto-patch/auto-patch.bash.in b/auto-patch/auto-patch.bash.in
--- a/auto-patch/auto-patch.bash.in
+++ b/auto-patch/auto-patch.bash.in
@@ -32,7 +32,7 @@ try_to_apply_patches()
         einfo "Check ${PATCH_DIR_FULL}"
     fi
     if [[ -d ${PATCH_DIR_FULL} ]] ; then
-        cd ${S}
+        cd "${S}" || die "Failed to cd into ${S}!"
         for i in "${PATCH_DIR_FULL}"/*.patch ; do
             if declare -f epatch >/dev/null ; then
                 epatch ${i}
@@ -41,7 +41,7 @@ try_to_apply_patches()
                 einfo "Applying ${i} ..."
                 patch -p1 -i "${i}" || die "Failed to apply ${i}!"
             fi
-            touch ${_ap_rememberfile}
+            touch "${_ap_rememberfile}" || die "Failed to touch ${_ap_rememberfile}!"
         done
         if [[ -e ${_ap_rememberfile} ]]; then
             issue_a_warning "will be"
