auto-patch: fall back to "patch -p1" if there is no epatch
"-p1" will very likely be the default for "eapply" anyway
in EAPI-6.

See https://wiki.gentoo.org/wiki/Future_EAPI/EAPI_6_tentative_features
    https://bugs.gentoo.org/show_bug.cgi?id=463768

diff --git a/auto-patch/auto-patch.bash.in b/auto-patch/auto-patch.bash.in
--- a/auto-patch/auto-patch.bash.in
+++ b/auto-patch/auto-patch.bash.in
@@ -34,9 +34,13 @@ try_to_apply_patches()
     if [ -d "${PATCH_DIR_FULL}" ] ; then
         cd ${S}
         for i in "${PATCH_DIR_FULL}"/*.patch ; do
-            # TODO 'epatch' will be available ONLY if current ebuild inherit eutils.eclass
-            # Need to do smth w/ this... :( It seems I have to copy-n-paste it here... :(
-            epatch ${i}
+            if declare -f epatch >/dev/null ; then
+                epatch ${i}
+            else
+                # sane default if no epatch is there
+                einfo "Applying ${i} ..."
+                patch -p1 -i "${i}" || die "Failed to apply ${i}!"
+            fi
             touch ${_ap_rememberfile}
         done
         if [ -e "${_ap_rememberfile}" ]; then
